### ISSUE TITLE
Crash while pressing A

### ISSUE THREAD

**Issue by David34920** [Dinones/Nintendo-Switch-Pokemon-Shiny-Hunter#37]
After some time, I got a weird stack when A button is pressed.
I have no idea of what is happening. It has happened two times, one after 88 resets and another one after more than 300 resets.

Here the stack:
```python
ERROR:dbus.proxies:Introspect error on :1.80:/org/bluez/hci0/dev_5C_0C_E6_29_FE_EC: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/nxbt/controller/server.py", line 308, in connection_reset_watchdog
    paths = self.bt.find_connected_devices(alias_filter="Nintendo Switch")
  File "/usr/local/lib/python3.8/dist-packages/nxbt/bluez.py", line 906, in find_connected_devices
    device_conn_status = device_props.Get(
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
^[[1;2A^[[1;2A^[[1;2A^CException in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "Shiny_Hunter.py", line 360, in <lambda>
    'thread': Thread(target=lambda: controller_control(Controller, shutdown_event), daemon=True)
  File "Shiny_Hunter.py", line 204, in controller_control
    elif aux_current_event == 'RESTART_GAME_1': restart_game_macro(controller)
  File "/home/david/git/Nintendo-Switch-Pokemon-Shiny-Hunter/Modules/Macros.py", line 98, in restart_game_macro
    controller.nxbt_manager.press_buttons(controller.controller_index, [Buttons.A])
  File "/usr/local/lib/python3.8/dist-packages/nxbt/nxbt.py", line 348, in press_buttons
    macro_id = self.macro(controller_index, macro, block=block)
  File "/usr/local/lib/python3.8/dist-packages/nxbt/nxbt.py", line 313, in macro
    if macro_id in finished:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by Dinones** [comment]
Hi! This issue is related to the `nxbt` library. I encounter the same problem from time to time, and it has already been reported in their repository.

In fact, any error related to `dbus.exceptions.DBusException` is linked to this, and there isn't much I can do about it.

You might want to update the `nxbt` library to see if the issue has already been resolved:

```pip install --upgrade nxbt```

**Comment by David34920** [comment]
Thanks for the information, I will follow nxbt to check when it will be fixed :)

**Comment by Dinones** [comment]
Thank you! If you find something interesting, please do not tell me via this thread or Discord.

You can also report it on their GitHub repository, and maybe they will fix it faster :)
